config/routes.rb
Rails.application.routes.draw do
  resources :patients do
    resources :exams
  end

  root to: "patients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
# frozen_string_literal: true

class Exam < ApplicationRecord
  belongs_to :patient

  belongs_to :point_po, class_name: 'Point', foreign_key: 'point_po_id', dependent: :destroy
  belongs_to :point_or, class_name: 'Point', foreign_key: 'point_or_id', dependent: :destroy
  belongs_to :point_a, class_name: 'Point', foreign_key: 'point_n_id', dependent: :destroy
  belongs_to :point_n, class_name: 'Point', foreign_key: 'point_a_id', dependent: :destroy

  accepts_nested_attributes_for :point_po
  accepts_nested_attributes_for :point_or
  accepts_nested_attributes_for :point_n
  accepts_nested_attributes_for :point_a

  def maxillary_depth_angle
    if point_po.x.nil? || point_po.y.nil? || point_or.x.nil? || point_or.y.nil? || point_n.x.nil? || point_n.y.nil? || point_a.x.nil? || point_a.y.nil?
      return nil
    end

    Calculus::MaxillaryDepthAngle.call(point_n, point_a, point_po, point_or)
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
	validates :name, presence: true
  has_many :exams
end

app/models/point.rb
class Point < ApplicationRecord
  has_one :exam
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: [:show, :edit, :update, :destroy]
  before_action :set_patient

  def index
    @exams = @patient.exams
    render json: @exams.includes(:point_po, :point_or, :point_a, :point_n), include: [:point_po, :point_or, :point_n, :point_a], methods: :maxillary_depth_angle
  end

  # GET /exams/1
  # GET /exams/1.json
  def show
  end

  def new
    @exam = Exam.new
    @exam.point_po = Point.new
    @exam.point_or = Point.new
    @exam.point_n = Point.new
    @exam.point_a = Point.new
    render  "_form", layout: false
  end

  def edit
    @exam = Exam.find(params[:id])
    render "_form", layout: false
  end

  # POST /exams
  # POST /exams.json
  def create
    @exam = Exam.new(exam_params)
    @exam.patient = @patient

    if @exam.save
      render json: @exam, include: [:point_po, :point_or, :point_n, :point_a], methods: :maxillary_depth_angle, status: :created
    else
      render json: @exam.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exams/1
  # PATCH/PUT /exams/1.json
  def update
    if @exam.update(exam_params)
      render json: @exam, include: [:point_po, :point_or, :point_n, :point_a], methods: :maxillary_depth_angle
    else
      render json: @exam.errors, status: :unprocessable_entity
    end
  end

  # DELETE /exams/1
  # DELETE /exams/1.json
  def destroy
    @exam.destroy
    respond_to do |format|
      format.html { head :no_content, notice: 'Exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam
      @exam = Exam.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exam_params
      params.require(:exam).permit(point_po_attributes: [:x,:y], point_or_attributes: [:x,:y], point_n_attributes: [:x,:y], point_a_attributes: [:x,:y])
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :birthdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/exams/_form.html.erb
<div class="modal-header">
  <h5 class="modal-title">Exam Form</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%= form_with(model: [@patient, @exam], data: { type: :json, exam: 'form' }) do |form| %>
  <div class="modal-body">
    <%= form.hidden_field  :patient_id, data: { 'exams-patient-id': @patient.id } %>
      <div class="row">
        <div class="col-md-12">
        <legend>Po point</legend>
          <div class="row">
            <%= form.fields_for :point_po do |po_form| %>
              <div class="col-md-3">
                <div class="form-group">
                  <%= po_form.label :x %>
                  <%= po_form.text_field :x, class: "form-control", data: { exams: 'field', 'field-name': 'po-x' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= po_form.label :y %>
                  <%= po_form.text_field :y, class: "form-control", data: { exams: 'field', 'field-name': 'po-y' } %>
                </div>
              </div>
            <% end -%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
        <legend>Or point</legend>
          <div class="row">
            <%= form.fields_for :point_or do |or_form| %>
              <div class="col-md-3">
                <div class="form-group">
                  <%= or_form.label :x %>
                  <%= or_form.text_field :x, class: "form-control", data: { exams: 'field', 'field-name': 'or-x' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= or_form.label :y %>
                  <%= or_form.text_field :y, class: "form-control", data: { exams: 'field', 'field-name': 'or-y' } %>
                </div>
              </div>
            <% end -%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
        <legend>N Point</legend>
          <div class="row">
            <%= form.fields_for :point_n do |n_form| %>
              <div class="col-md-3">
                <div class="form-group">
                  <%= n_form.label :x %>
                  <%= n_form.text_field :x, class: "form-control", data: { exams: 'field', 'field-name': 'n-x' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= n_form.label :y %>
                  <%= n_form.text_field :y, class: "form-control", data: { exams: 'field', 'field-name': 'n-y' } %>
                </div>
              </div>
            <% end -%>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
        <legend>A point</legend>
          <div class="row">
            <%= form.fields_for :point_a do |a_form| %>
              <div class="col-md-3">
                <div class="form-group">
                  <%= a_form.label :x %>
                  <%= a_form.text_field :x, class: "form-control", data: { exams: 'field', 'field-name': 'a-x' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= a_form.label :y %>
                  <%= a_form.text_field :y, class: "form-control", data: { exams: 'field', 'field-name': 'a-y' } %>
                </div>
              </div>
            <% end -%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save</button>
  </div>
<% end %>

app/views/exams/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p>
      <strong>Patient:</strong>
      <%= @patient.name %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    Point Po <br> <%= "x: #{@exam.point_po.x}, y: #{@exam.point_po.y}" %>
  </div>
  <div class="col-md-2">
    Point Or <br> <%= "x: #{@exam.point_or.x}, y: #{@exam.point_or.y}" %>
  </div>
  <div class="col-md-2">
    Point N <br> <%= "x: #{@exam.point_n.x}, y: #{@exam.point_n.y}" %>
  </div>
  <div class="col-md-2">
    Point A <br> <%= "x: #{@exam.point_a.x}, y: #{@exam.point_a.y}" %>
  </div>
  <div class="col-md-2">
    Angle <br> <%= @exam.maxillary_depth_angle %>
  </div>
</div>

<div class="row">
  <div class="col-md-12" data-view3d='wrapper'>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="actions">
      <%= link_to 'Back', patient_path(@patient), class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>

  <body>

  </body>
</html>


<!doctype html>
<html lang="en">
  <head>
    <title>MaxillaryDepth</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-eval': false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-eval': false %>
  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">Maxillary Depth</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Patients', patients_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <main role="main" class="container">

    <%= yield %>

  </main><!-- /.container -->

  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-3">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary"  %>
    <%= link_to 'Back', patients_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td>
          <div class="float-right">
          <%= link_to 'Show', patient, class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-sm btn-secondary" %>
          <%= link_to 'Destroy', patient, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Patient', new_patient_path, class: "btn btn-primary" %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Point Po</th>
      <th>Point Or</th>
      <th>Point N</th>
      <th>Point A</th>
      <th>Angle</th>
      <th></th>
    </tr>
  </thead>
  <tbody data-exams='exams' data-exams-patient-id='<%= @patient.id %>'>
  </tbody>
</table>


<%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-secondary float-right" %>
<%= button_tag 'Add Exam', type: 'button', class: "btn btn-primary float-right", data: { exams: 'btn-create'} %>
<%= link_to 'Back', patients_path, class: "btn btn-secondary"  %>


<div class="modal" tabindex="-1" role="dialog" data-exams='modal'>
  <div class="modal-dialog" role="document">
    <div class="modal-content">

    </div>
  </div>
</div>